In [1]:
# Mount Google Drive
from google.colab import drive # import drive from google colab

ROOT = "/content/drive"     # default location for the drive
print(ROOT)                 # print content of ROOT (Optional)

drive.mount(ROOT, force_remount=True)           # we mount the google drive at /content/drive

/content/drive
Mounted at /content/drive


In [ ]:
%cd 'drive/My Drive/Workspaces/Nnfs'

In [6]:
import numpy as np
inputs = [1.2,5.1,2.1]
weights = [3.1,2.1,8.7]
bias = 3
output = bias + np.sum(np.array(inputs) * np.array(weights))
output

35.7

In [11]:
inputs = [1,2,3,2.5]
weights1 = [0.2,0.8,-0.5,1.0]
weights2 = [0.5,-0.91,0.26,-0.5]
weights3 = [-0.26,-0.27,0.17,0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

output = [bias1 + np.sum(np.array(inputs) * np.array(weights1)),
          bias2 + np.sum(np.array(inputs) * np.array(weights2)),
          bias3 + np.sum(np.array(inputs) * np.array(weights3))]

output

[4.8, 1.21, 2.385]

In [16]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]

layer_outputs = []
for bias, weights in zip(bias, weights):
  neuron_output = 0 
  for idx, weight in enumerate(weights):
    neuron_output += weight * inputs[idx]

  neuron_output += bias
  layer_outputs.append(neuron_output)

layer_outputs


[4.8, 1.21, 2.385]

In [22]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]
layer_outputs = np.dot(weights,inputs) + bias
print(layer_outputs)

[4.8   1.21  2.385]


In [25]:
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]

weights2 = [ [0.1, -0.14, 0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]            
]

bias2 = [-1,2,-0.5]
layer1_outputs = np.dot(inputs, np.array(weights).T) + bias

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + bias2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


# Making layer object


In [29]:
X =  [[1,2,3,2.5],
      [2.0,5.0,-1.0,2.0],
      [-1.5,2.7,3.3,-0.8]]


class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[-0.22749659 -0.16677017 -0.17337952  0.27567213  0.33804504]
 [-0.59987721 -0.00230754 -0.44337468 -0.0857753   0.48476806]
 [ 0.35602002  0.03474781 -0.40738723 -0.30393727  0.04560125]]
[[-0.08388191  0.03410065]
 [-0.0863461   0.06788293]
 [ 0.08352596  0.08570044]]
