In [ ]:
# Mount Google Drive
from google.colab import drive # import drive from google colab

ROOT = "/content/drive"     # default location for the drive
print(ROOT)                 # print content of ROOT (Optional)

drive.mount(ROOT, force_remount=True)           # we mount the google drive at /content/drive

/content/drive
Mounted at /content/drive


In [ ]:
%pwd
%cd 'drive/My Drive/Workspaces/Nnfs'

/content/drive/My Drive/Workspaces/Nnfs


In [ ]:
import numpy as np
inputs = [1.2,5.1,2.1]
weights = [3.1,2.1,8.7]
bias = 3
output = bias + np.sum(np.array(inputs) * np.array(weights))
output

35.7

In [ ]:
inputs = [1,2,3,2.5]
weights1 = [0.2,0.8,-0.5,1.0]
weights2 = [0.5,-0.91,0.26,-0.5]
weights3 = [-0.26,-0.27,0.17,0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

output = [bias1 + np.sum(np.array(inputs) * np.array(weights1)),
          bias2 + np.sum(np.array(inputs) * np.array(weights2)),
          bias3 + np.sum(np.array(inputs) * np.array(weights3))]

output

[4.8, 1.21, 2.385]

In [ ]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]

layer_outputs = []
for bias, weights in zip(bias, weights):
  neuron_output = 0 
  for idx, weight in enumerate(weights):
    neuron_output += weight * inputs[idx]

  neuron_output += bias
  layer_outputs.append(neuron_output)

layer_outputs


[4.8, 1.21, 2.385]

In [ ]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]
layer_outputs = np.dot(weights,inputs) + bias
print(layer_outputs)

[4.8   1.21  2.385]


In [ ]:
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]

weights2 = [ [0.1, -0.14, 0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]            
]

bias2 = [-1,2,-0.5]
layer1_outputs = np.dot(inputs, np.array(weights).T) + bias

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + bias2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


# Making layer object


In [ ]:
import numpy as np

X =  [[1,2,3,2.5],
      [2.0,5.0,-1.0,2.0],
      [-1.5,2.7,3.3,-0.8]]


class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.41539245  0.13807719  0.45012299  0.57883189  0.36537224]
 [-0.51988274 -0.80470426 -0.21401013  0.82535934  0.36244305]
 [ 0.4713901  -0.67377721  0.46691783  0.43786339 -0.0300448 ]]
[[ 0.04573957  0.00663354]
 [-0.04114991 -0.15707187]
 [ 0.00180242  0.01309348]]


## Rectified Linear Unit ReLU activation function

In [ ]:
# ! pip install nnfs
!nnfs


Neural Networks from Scratch in Python Tool.

Basic usage:
nnfs command [parameter1 [parameter2]]

Detailed usage:
nnfs info | code video_part [destination]

Commands:
  info    Prints information about the book
  code    Creates a file containing the code of given video part
          in given location. Location is optional, example:
          nnfs code 2 nnfs/p02.py
          will create a file p02.py in a nnfs folder containing
          the code of part 2 of video tutorial
    


In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X =  [[1,2,3,2.5],
      [2.0,5.0,-1.0,2.0],
      [-1.5,2.7,3.3,-0.8]]

X,y = spiral_data(100,3)      

inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []

for i in inputs:
  output.append(max(0,i))

print(output)

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0,inputs)


layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()
layer1.forward(X)
# print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]


In [ ]:
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y